format_version = 1

[project]
name = "testmotor"
ioc_file = "testmotor.ioc"

[dependencies]
packages = [
    "MotorDrivers::DJI",
    "MotorDrivers::Controller",
    "MotorDrivers::DM",
    "memory::StaticArena",
    "utils",
]
